FROM node:12
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install -g gatsby-cli
COPY ./SimpleCMSWeb/package.json /app/
COPY ./SimpleCMSWeb/package-lock.json /app/
RUN npm install
COPY ./SimpleCMSWeb/ /app/