  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    backend:
      build:
        context: .
        dockerfile: Dockerfile-backend
      command: ./Scripts/run-backend-docker-compose.sh
      volumes:
        - .:/code
      environment:
        - DOKCER-COMPOSE-ENV=true
      ports:
        - "8000:8000"
      depends_on:
        - db
    frontend:
      build:
        context: .
        dockerfile: Dockerfile-frontend
      command: ./Scripts/run-frontend-docker-compose.sh
      volumes:
        - .:/app
      ports:
        - "8080:8080"
      depends_on:
        - backend
