  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: ./Scripts/run-docker-compose.sh
      volumes:
        - .:/code
      environment:
        - DOKCER-COMPOSE-ENV=true
      ports:
        - "8000:8000"
      depends_on:
        - db

