# Generated by Django 3.0.7 on 2020-06-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('blog_text', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleCmsAPI.User')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleCmsAPI.BlogPost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleCmsAPI.User'),
        ),
    ]
