# Generated by Django 3.0.7 on 2020-06-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleCmsAPI', '0002_auto_20200615_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='header',
            new_name='title',
        ),
    ]
